### ISSUE TITLE
Convert default branch to be named 'main'

### ISSUE THREAD

**Issue by danisyellis** [indeedeng/starfish#107]
Now that GitHub has finalized their tooling and process for renaming the default branch, let's change 'master' to 'main'.
Some documentation here https://github.com/github/renaming

**Comment by SheriffHobo** [comment]
The PR for the change is ready for review.

**Comment by kevindigo** [comment]
It seemed like this accidentally got closed, so I reopened it.

**Comment by danisyellis** [comment]
Forgot to close this when I approved the PR. Thanks @SheriffHobo :-D
