### ISSUE TITLE
Add More Tests

### ISSUE THREAD

**Issue by hnarasaki** [indeedeng/starfish#13]
Add more tests.

**Comment by danisyellis** [comment]
Are there any tests in particular you think would be useful to add?

For anyone wanting to work on this: there is currently a test.js file that is hooked up and working, with 1 super-basic test. More are welcome.
If @hnarasaki doesn't add more detail to this issue themself, I'll try to flesh it out at some point.

**Comment by hackily** [comment]
There's quite a few helper functions that should have tests written for them, assertions can be written for both the happy and unhappy paths.
My diff https://github.com/indeedeng/starfish/pull/48 exports these helper functions into the test file and offers another very basic example for one of these helper functions, and leaves plenty of room for other contributors to flesh out the rest of the tests.

**Comment by thisisamank** [comment]
Hi, i would like to work on it 😃

**Comment by danisyellis** [comment]
Hi @thisisamank. That would be great.
You may want to wait a few days to start, until I've resolved #48, to avoid potential merge conflicts.

**Comment by thisisamank** [comment]
okay 👍

**Comment by danisyellis** [comment]
Okay @thisisamank. I've merged in the relevant PRs, so feel free to get started. Hackily's changes should make writing tests easier. 

I also just created #59 because we'd like to eventually switch from Mocha to Jest for our test suite.
If you'd like to work on that one, leave a comment in there and I'll assign you. Otherwise, feel free to write your tests in Mocha, it should be pretty easy to convert them when we switch. 

Thanks for contributing :-)

**Comment by danisyellis** [comment]
Someone has asked to work on 59, and says they should be done with it today or tomorrow.
So I'll assign this one to you @thisisamank and you should write your tests using Jest.

**Comment by danisyellis** [comment]
Functions that currently (once an open PR is merged in) have tests:
    filterResponseForImportantEvents,	
    getOrThrow 

Functions that currently need tests:
    createIdObject,	
    fetchPageOfDataAndFilter,	
    fetchUserDataAndAddToCSV,	
    filterContributorByTime,	
    parseDatesFromArgv

**Comment by AndreRSFC** [comment]
@danisyellis Hello, I would like to test the following functions: createObject, filterContributorByTime and parseDatesFromArgv.

**Comment by thisisamank** [comment]
I am really sorry for this, but my computer has got some serious problems
and by the end of next week it will be fixed...you know lockdown and all
has made the process slow...so until then i won't be able to write code. I
can start working from 24th oct...or may be please assign it to someone
else who is interested.
Thanks and sorry again!

**Comment by jmakhack** [comment]
Hi @danisyellis, if another developer is needed to write the remaining tests, I can pick this issue up.

Looks like there is currently a PR open for the tests for `createIdObject`, `filterContributorByTime` and `parseDatesFromArgv`.
I can help write tests for the remaining functions: `fetchPageOfDataAndFilter` and `fetchUserDataAndAddToCSV`.

**Comment by danisyellis** [comment]
Thanks for the PRs AndreRSFC and jmakhack, take a look at your PRs for some code review.

@thisisamank no worries at all. I really appreciate that you let us know so that other people could work on it :-)

**Comment by danisyellis** [comment]
Most functions have tests now, so I'm closing this general issue and will open a new, more specific one if we decide we need any more tests  :-)
