### ISSUE TITLE
Update README.md with Project Structure Information

### ISSUE THREAD

**Issue by hnarasaki** [indeedeng/starfish#15]
It could be helpful for new contributors to have a Project Structure section in the README.md explaining the structure, like what each folder/file does.

Example: https://github.com/twilio-labs/open-pixel-art/blob/master/CONTRIBUTING.md

**Comment by danisyellis** [comment]
That's a cool idea. Starfish is pretty simple.

All of the code is in index.js
Everything else is text files, the gitignore (to tell git what to ignore), a template for making the environment variables, a test file (with only 1 test so far), and the package.json (which is a node configuration file). 
When you run npm install, you'll also get a folder called node_modules added to your code locally. That folder contains all of the dependencies - libraries of code starfish is using - and you can ignore all of it.

Feel free to add this info to the "Contributing" section of the README if you like.
