### ISSUE TITLE
Set up linting

### ISSUE THREAD

**Issue by dejongnj** [indeedeng/starfish#19]
Linting will provide a way for contributors to make PRs with more confidence that they are meeting the coding standards of the project. This is easy to setup, but should probably be done by someone who is heading up the project so that we can adhere to their rules/style preferences.

**Comment by kevindigo** [comment]
Big +1 on this. Great idea.

**Comment by danisyellis** [comment]
Agreed. That's a great idea. We'll add it to our TODO list. Thanks!

**Comment by danisyellis** [comment]
PRs #37 and #31 fix this issue
