### ISSUE TITLE
Remove hard-coding of github id column

### ISSUE THREAD

**Issue by dejongnj** [indeedeng/starfish#20]
Currently this project hardcodes the column from which we get the github id here: https://github.com/indeedeng/starfish/blob/dc651c846bbbe1bc6eefee70a24cdf44383c59a2/index.js#L50

We should allow the user to specify which line they get it from. I figured this out while trying to run with test data (copy and pasted from readme.md and using my own details and getting zero responses). Once I added a dummy first column, it worked. What tipped me off was the use of google forms which adds a first column which is a timestamp.

I'd be happy to work on this :)

EDIT: This is the line that hard-codes it:
https://github.com/indeedeng/starfish/blob/dc651c846bbbe1bc6eefee70a24cdf44383c59a2/index.js#L70

**Comment by kevindigo** [comment]
This sounds great to me. How would you envision passing the desired column value into the code?

**Comment by dejongnj** [comment]
The .env.template has a property `CSV_COLUMN_NUMBER_FOR_GITHUB_ID`. We could just use that as a first step

**Comment by danisyellis** [comment]
Yes! Looking over my code briefly, it looks like I use CSV_COLUMN_NUMBER_FOR_GITHUB_ID to make `githubIdColumnNumber` on line 12
https://github.com/indeedeng/starfish/blob/dc651c846bbbe1bc6eefee70a24cdf44383c59a2/index.js#L12
and then I use `githubIdColumnNumber` to make `idObject.github` on line 122, 
https://github.com/indeedeng/starfish/blob/dc651c846bbbe1bc6eefee70a24cdf44383c59a2/index.js#L122
but then I don't actually use idObject.github anywhere. Oops. I think that was a refactor I started with the intention of removing hard-coding of the github id column, but I somehow failed to finish it. ??? Great catch! 

Please do work on this if you're interested. I'd really appreciate it :-D

**Comment by IngridGdesigns** [comment]
will work on this issue
