### ISSUE TITLE
Change the array used to check for duplicate ids into a set (edited issue title to reflect the change we decided on)

### ISSUE THREAD

**Issue by dejongnj** [indeedeng/starfish#21]
When checking for duplicated IDs we push existing ids into an array: https://github.com/indeedeng/starfish/blob/dc651c846bbbe1bc6eefee70a24cdf44383c59a2/index.js#L35

Changing the data structure to an object will allow for O(1) lookup time instead of O(n) having to look through the whole array to check which will speed up the process and scale a little better. It could also reduce/simply the logic needed to identify duplicated github ids.

**Comment by kevindigo** [comment]
Would a Set be even better than an object?

**Comment by dejongnj** [comment]
Nice! I like that idea better. Even though an object may be slightly more performant than Set, I think Set is semantically a better choice and its implementation (under the hood) should still be O(1)

**Comment by danisyellis** [comment]
Sounds good to me.
