### ISSUE TITLE
Starfish: Change how timezone offset is passed in and handled

### ISSUE THREAD

**Issue by danisyellis** [indeedeng/starfish#29]
The way we are handling the config TIMEZONE_OFFSET may only work for time zones west of UTC+0, and is confusing in the sense that a UTC-06 offset is entered as a positive 06. Also, it doesn't currently allow for true timezones– instead, it only allows a constant offset from UTC. 

We should probably rename the config variable to something like "TIMEZONE", and allow the values to be any named timezone or offset value that moment accepts. For example, "America/Los_Angeles", "-04", "+0630", or "JST". 

The meaning would be: Contributions would be assigned to a day based on boundaries of midnight in the specified time zone.

**Comment by jeffwilcox** [comment]
I'm using the npm `luxon` in my project today and so when I incorporated the starfish approach, I went with configuring an IANA timezone, giving me this ugly but functional way of having the appropriate boundary for the month local to our corp hq.

```
  const now = new Date();
  const start = DateTime.fromObject({ year: now.getFullYear(), month: 1 + now.getMonth(), zone: ianaZone });
  return { start: start.toJSDate(), end: start.plus({ months: 1 }).toJSDate() };
```

**Comment by IngridGdesigns** [comment]
I will work on this issue

**Comment by IngridGdesigns** [comment]
Fixed issue and added/edited TIMEZONE and how to use it [here is the PR]( https://github.com/indeedeng/starfish/pull/36)

**Comment by mjpitz** [comment]
You could consider leveraging the `TZ` environment variable employed by docker and many other systems.

**Comment by kevindigo** [comment]
Using TZ is an interesting idea. However, in this case, I think one of our design goals is to be able to use a different timezone for the midnight boundary than the one that the executing machine is configured to use. For example, a developer in Florida might want to use UTC, or Los Angeles time, as the boundary during testing.

**Comment by jeffwilcox** [comment]
Time is hard! We were wondering about this, too - MSFT is very Redmond-centric (we love 98052!), so for FOSS Fund we're using Redmond time boundaries for a month of contributions... but realize... that's not ideal. Better would be for the HR systems to tell us where a person's home timezone is and respect that.

**Comment by kevindigo** [comment]
@jeffwilcox : That's a cool idea. Glancing at the code, I don't think it would be too hard to add a config setting to indicate a column in the input CSV that would indicate the time zone for each contributor. We would want that to be optional, so orgs could continue to use the global setting that starfish already has. There would be a slight data gap/overlap for the month that an org switched from one method to the other, but I can't think of any other concerns around that.  

If you're interested in that feature, feel free to create a new issue here requesting it. You could even put up a PR if you wanted ;)

**Comment by jeffwilcox** [comment]
I'd love to contribute, but unfortunately have had to diverge from using starfish due to significant rate limiting over the 30,000 different accounts I'm grabbing data on... so I'm messing with a similar codebase now but yet different.
