### ISSUE TITLE
Add functionality for a "opt-out" users list.

### ISSUE THREAD

**Issue by SheriffHobo** [indeedeng/starfish#30]
We have heard from a number of contributors that they do not wish to be part of the FOSS fund voting Slack channel. With that in hand, we could use a function that allows the entry of an "opt-out" list that would be compared to the full list of contributors, then it would return a revised list of contributors minus the "opt-out" folk. The list of opt-out users needs to be manageable as well, in case someone does want to jump back in.

Input opt-out users > Starfish runs & compares it's users master list to opt-out list > Returns a modified user list to use.

**Comment by danisyellis** [comment]
I wonder whether this would be a generally useful feature or if it's more Indeed specific and something we should just implement locally. @DuaneOBrien do you have any thoughts from talking with other OSPOs?
Anyone else reading this from another institution, please chime in with whether or not you'd like this functionality in Starfish.

**Comment by jeffwilcox** [comment]
Our notifications asking people to vote (we don't use slack, so, for us, it's e-mail) and also for awareness uses a company "mail campaign" system - we have to provide unsubscribe links always - and we've had 14 people unsubscribe, which is a bummer. :(

**Comment by danisyellis** [comment]
@SheriffHobo after thinking about this and talking to a few people, we think it makes more sense to simply

- have a separate sheet(page) in our google spreadsheet of GitHub Ids that contains only the employees who haven't opted out of FOSS Fund voting

- feed into Starfish that list of only the potential contributors that you care about.

There's no need to have Starfish look up the contributors who won't be voting. And you can easily re-add people into the spreadsheet if need-be.
