### ISSUE TITLE
Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [indeedeng/starfish#52]
@danisyellis

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.
Also hopping between the information will be quite ease

I would like to work on this issue.

Cheers,

**Comment by danisyellis** [comment]
Hi @ng29.
Thanks for submitting this issue. We thought about it and decided that we don't want a Table of Contents for the README at this time.
The README is still pretty small, and if we had a Table of Contents, we'd have to make sure to keep it updated any time we changed anything. Thanks anyway!
