### ISSUE TITLE
Allow filtering based on action types within event types

### ISSUE THREAD

**Issue by kevindigo** [indeedeng/starfish#58]
Starfish currently can be configured to count contributions based on their event type, like "PullRequestEvent". It would be nice to further be able to count (or not count) those events based on the event action. For example, to include PullRequestEvent "closed" events but not "opened" events. 

I would propose that the existing event type environment variable could be extended in a backward-compatible way. If only an event type is specified, that would mean that all action types would be included. But if the entry had both an event type and an event action, like "PullRequestEvent.opened", that would mean that only pull request open actions would be counted. Listing multiple action types for a given event type would treat them as connected by "OR", just as listing multiple event types are already connected with an implicit OR.

**Comment by danisyellis** [comment]
To add a bit more detail:
This will be a change to the GITHUB_IMPORTANT EVENTS environment variable and how it's used. After this change, if the user decides to create a custom list of events, each of those events can contain event type or not. It can be a mix. An example value for `GITHUB_IMPORTANT EVENTS` would be `“PullRequestEvent.opened, PullRequestEvent.closed, CommitCommentEvent”` etc.

The event type can be found in the response from GitHub in event.type and the event action can be found in event.payload.action

**Comment by Himanshu-Modi** [comment]
Hey @danisyellis i wanna work on this. Can i take this.

**Comment by danisyellis** [comment]
Sure! Thanks. Let me know if you have any questions.

**Comment by Himanshu-Modi** [comment]
Basically my approach of filtering event is that if the event doesn't contain a type then compare and add it to Important events.
else if the event contains type then we compare the (event + event type) and add them if they matches .

I have implemented it can i make a pull request.

**Comment by danisyellis** [comment]
That sounds like the right approach.

Please do submit your pull request. We'll take a look and let you know if there's anything that needs to be changed.

Before submitting the PR, remember to 
a) make sure it runs and gives the output you expect
b) run the linter and make sure everything passes
c) run the tests and make sure everything passes
d) once you push it to github, make sure that your branch can be auto-merged (there are no merge conflicts)
