### ISSUE TITLE
Switch test suite from Mocha to Jest

### ISSUE THREAD

**Issue by danisyellis** [indeedeng/starfish#59]

**Comment by JoeAmedeo** [comment]
I would be willing to tackle this one, should be able to get it done tomorrow.

**Comment by danisyellis** [comment]
Sounds good. Thanks @JoeAmedeo 
FYI, we realized yesterday that currently, when you run the tests in mocha, they hang (the process never finishes even though it's done running the tests). Until we fix the underlying cause, the same thing will likely happen when you switch it over to Jest. As long as the tests run in Jest correctly, it's fine for now if the process hangs. 

(We'll probably fix it by moving most of the code from index.js to a separate starfish.js and then have both the tests and index.js  require the new file.)
