### ISSUE TITLE
replace Moment.js with Luxon

### ISSUE THREAD

**Issue by danisyellis** [indeedeng/starfish#60]
Moment is in a semi-deprecated state now. They recommend using something else in most cases.
We've tried out [Luxon](https://moment.github.io/luxon/) a bit and like it, so we're looking to switch Starfish to use Luxon everywhere that we're currently using Moment.

If you take up this issue, be sure to update the README to reflect any changes you make to how a user should fill out the TIMEZONE env variable.

**Comment by AndreRSFC** [comment]
I would like to try to resolve this issue :)

**Comment by AndreRSFC** [comment]
Any proposal for improvement or adjustment that I am totally willing to make, just let me know :)
