### ISSUE TITLE
Extract the entire Contributing section of the README into a Contributing.MD

### ISSUE THREAD

**Issue by danisyellis** [indeedeng/starfish#83]
Now that it's gotten longer, it makes sense to make it a separate file. Plus, that's good practice for an open source project to have a Contributing.MD

The new file should contain everything that's currently in the “Contributing” section of the README, and probably nothing else.

The README should be left with the header that says Contributing and a new sentence mentioning that we welcome contributors and they should look at our CONTRIBUTING.MD for information and requirements, with a link to the file.

**Comment by suveshmoza** [comment]
Hello can I help you with this issue?

**Comment by danisyellis** [comment]
That would be great @suveshmoza Thank you!

I just edited the instructions above to be a bit more specific, so make sure to re-read it before you start :-)
