### ISSUE TITLE
Rename ALTERNATE_ID to ID_TO_LOG_OUT or ID_FOR_OUTPUT or something like that

### ISSUE THREAD

**Issue by danisyellis** [indeedeng/starfish#85]
I think this change will make it more obvious what that ID is for.

As part of this change, update the README in any way necessary to make it as understandable as possible that this is controlled by the CSV and the number you put in the ENV variable, not in the code.

**Comment by kevindigo** [comment]
Between those 2 options, I prefer ID_FOR_OUTPUT.
