### ISSUE TITLE
Add configuration option to allow custom lists of important events.

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/starfish#9]
The function filterResponseForImportantEvents relies on a hard-coded lists of events that we believe are important. This list of events should be moved to a configuration option that allows the list of events to be customized. By way of example, our list of events specifically excludes PushEvent, but future users may want to include it.

The simplest version of this would be to add a new variable to the .env.template file:
- List of Important Events ([The,List,Of,Events,That,We,Predefine])

Update filterResponseForImportantEvents to use the new .env variable.

Add documentation to the README.md for using the new .env variable.

**Comment by rajitha1998** [comment]
Hi can I try this issue?

**Comment by danisyellis** [comment]
Sure! Let me know if you have any questions.

**Comment by hwang381** [comment]
Anyone actually taking this? If not may I take a stab?

**Comment by danisyellis** [comment]
oh, that's strange. Someone claimed this issue but their comment is gone now. I guess they changed their mind and deleted it without saying anything.
Thanks for the PR! I'm heading out for the day, but I'll take a look at it soon.

**Comment by hwang381** [comment]
@danisyellis May I get an eye on the CR? Thank :)
